[[picturalib]]
arch = "x86_64"
git-tree-sha1 = "1f83b7ecca3ec9b054fac8e3c337c08c7f5cd420"
libc = "glibc"
os = "linux"

    [[picturalib.download]]
    sha256 = "30ac9434a4e48ec6f36bcf3467bc671f3c0fce94ac089a63835f94eec29df64c"
    url = "https://github.com/Zhurgut/Pictura.jl/releases/download/v0.1.0/picturalib-x86_64-linux.tar.gz"
[[picturalib]]
arch = "x86_64"
git-tree-sha1 = "61c0414e54148f312da8ee99e6c257d33c3d7daf"
os = "windows"

    [[picturalib.download]]
    sha256 = "c5d353c15883f0ca636f0f3b1219277c99d5864744efae5e65008d42164cf401"
    url = "https://github.com/Zhurgut/Pictura.jl/releases/download/v0.1.0/picturalib-x86_64-windows.tar.gz"
