[[picturalib]]
arch = "x86_64"
git-tree-sha1 = "167274331c2ffd4ca8e06bbd034f4733036b77c4"
libc = "glibc"
os = "linux"

    [[picturalib.download]]
    sha256 = "cf4a99ad20e3b2b1d17afcbd477667dac8018c4bcd1c0fc5fad840b3c13c7a96"
    url = "https://github.com/Zhurgut/Pictura.jl/releases/download/v0.1.0/picturalib-x86_64-linux.tar.gz"
[[picturalib]]
arch = "x86_64"
git-tree-sha1 = "babf132a777db203697cf58d752fd4759dfab816"
os = "windows"

    [[picturalib.download]]
    sha256 = "7d03d2a11de02869d7404c3a3f5160ba901336b1c66e7f86b89701cac4ed442b"
    url = "https://github.com/Zhurgut/Pictura.jl/releases/download/v0.1.0/picturalib-x86_64-windows.tar.gz"
