
#
# functions to parse source files and get names and values that are to be exported
#

function get_constants(file_string)
    cns = collect(eachmatch(r"const (?<name>[A-Z]*?) = (?<value>\d*?);", file_string))
    return [(name=cn[:name], value=cn[:value]) for cn in cns]
end

function get_functions(file_string)
    fns = collect(eachmatch(r"pub export fn (?<name>.*?)\((?<args>[^\{]*)\) (?<return_type>.*?) \{", file_string))
    names = [f[:name] for f in fns]
    raw_args = [f[:args] for f in fns]
    args = [get_args(arg) for arg in raw_args]
    return_types = [f[:return_type] for f in fns]
    
    return [(name=names[i], args=args[i], return_type=return_types[i]) for i=eachindex(fns)]
end

function get_args(args_string)
    args = collect(eachmatch(r"(?<name>\w+): (?<type>[^,\(]+(\([^\(\)]*\))?[^,]+)", args_string))
    args = [(name=arg[:name], type=arg[:type]) for arg in args]
    args = [is_function_type(arg.type) ? (name=arg.name, type="*const fn", fn_arg=get_function_type_arg(arg.type)) : arg for arg in args]
    return args
end

is_function_type(arg) = contains(arg, "*const fn")

function get_function_type_arg(s)
    m = match(r"\*const fn \((?<args>.*?)\) callconv\(.c\) (?<return_type>.+)", s)
    return (type="*const fn", args=get_args(m[:args]), return_type=m[:return_type])
end



function translate_type(s, julia=false)
    return if s == "u32"
        julia ? "UInt32" : "uint32_t"
    elseif s == "*const fn"
        julia ? "Ptr{Cvoid}" : error("noo!")
    elseif s == "ErrorCode"
        julia ? "UInt32" : "uint32_t"
    elseif s == "root.vulkan.PFN_vkVoidFunction"
        julia ? nothing : "PFN_vkVoidFunction"
    elseif s == "root.vulkan.VkInstance"
        julia ? nothing : "VkInstance"
    elseif s == "root.vulkan.VkPhysicalDevice"
        julia ? nothing : "VkPhysicalDevice"
    elseif s == "root.vulkan.VkDevice"
        julia ? nothing : "VkDevice"
    elseif s == "root.vulkan.VkQueue"
        julia ? nothing : "VkQueue"
    elseif s == "*root.vulkan.VkCommandBuffer"
        julia ? nothing : "VkCommandBuffer*"
    elseif s == "i32"
        julia ? "Int32" : "int32_t"
    elseif s == "[*:0]const u8"
        julia ? "Cstring" : "const char*"
    elseif s == "?[*][*:0]const u8"
        julia ? nothing : "const char**"
    elseif s == "Image"
        julia ? "Ptr{Cvoid}" : "Image"
    elseif s == "?Image"
        julia ? "Ptr{Cvoid}" : "Image"
    elseif s == "void"
        julia ? "Cvoid" : "void"
    elseif s == "?*anyopaque"
        julia ? "Ptr{Cvoid}" : "void*"
    elseif s == "[*]u32"
        julia ? "Ptr{UInt32}" : "uint32_t*"
    elseif s == "?[*]u32"
        julia ? "Ptr{UInt32}" : "uint32_t*"
    elseif s == "bool"
        error("bool not unviersally the same")
    elseif s == "f32"
        julia ? "Float32" : "float"
    elseif s == "f64"
        julia ? "Float64" : "double"
    elseif s == "u64"
        julia ? "UInt64" : "uint64_t"
    elseif s == "i64"
        julia ? "Int64" : "int64_t"
    elseif s == "?*f32"
        julia ? "Ptr{Float32}" : "float*"
    elseif s == "?*i32"
        julia ? "Ptr{Int32}" : "int32_t*"
    elseif s == "u8"
        julia ? "UInt8" : "uint8_t"
    elseif s == "*u32"
        julia ? "Ptr{UInt32}" : "uint32_t*"
    elseif s == "*i32"
        julia ? "Ptr{Int32}" : "int32_t*"
    else
        error("$s undefined, cannot translate type")
    end
    
end


#
# functions to translate zig into C for the picturalib.h header
#
function translate_constant(c)
    return "#define $(c.name) $(c.value)\n"
end


function translate_args(args)
    out = ""
    for (i, a) in enumerate(args) 
        if i > 1 out *= ", " end

        if a.type == "*const fn"
            out *= translate_function_type_arg(a.name, a.fn_arg)
        else
            out *= "$(translate_type(a.type)) $(a.name)"
        end
    end
    out
end

function translate_function(f)
    return "$(translate_type(f.return_type)) $(f.name)($(translate_args(f.args)));\n"
end

function translate_function_type_arg(name, arg)
    return "$(translate_type(arg.return_type)) (*$name)($(translate_args(arg.args)))"

end








function write_c_header(out, constants, functions)
    write(out, "#ifndef PICTURALIBH\n#define PICTURALIBH\n\n")
    write(out, """#include "vulkan/volk.h"\n""")
    write(out, "#include <inttypes.h>\n\n")
    
    for c in constants
        write(out, translate_constant(c))
    end

    write(out, "\n")
    write(out, "typedef void* Image;\n\n")

    for f in functions
        write(out, translate_function(f))
    end

    write(out, "\n#endif")
end








function write_jl_module(out, constants, functions)
    write(out, """
# file generated by lib/generate_header_and_julia_bindings.jl

module PicturaLib

using Artifacts

if Sys.iswindows()
	dev_path = joinpath(@__DIR__, "..", "lib", "zig-out", "bin", "pictura.dll")
	artf_path = joinpath(artifact"picturalib", "bin", "pictura.dll")
else
	dev_path = joinpath(@__DIR__, "..", "lib", "zig-out", "lib", "libpictura.so")
	artf_path = joinpath(artifact"picturalib", "lib", "libpictura.so")
end
const lib = if isfile(dev_path) dev_path else artf_path end
chmod(lib, 0o755)

""")

    for c in constants
        write(out, "const $(c.name) = $(c.value)\n")
    end
    write(out, "export ")
    for c in constants[1:end-1]
        write(out, "$(c.name), ")
    end
    write(out, "$(constants[end].name)\n\n")
    
    for f in functions
        
        if !contains(f.name, "_vk_") && f.name != "init2" 
            write(out, "\n")

            argnames = join([a.name for a in f.args], ", ")
            rhs_args = "\n" * join(["\t\t$(a.name)::$(translate_type(a.type, true))" for a in f.args], ",\n") * "\n\t"
            if length(f.args) == 0
                rhs_args = ""
            end

            for a in f.args
                if a.type == "*const fn"
                    args = join(["$(translate_type(a.type, true))" for a in a.fn_arg.args], ", ") * ","
                    write(out, "# your_julia_function($(join(["$(a.name)::$(translate_type(a.type, true))" for a in a.fn_arg.args], ", ")))\n")
                    write(out, "# $(a.name) = @cfunction(your_julia_function, $(translate_type(a.fn_arg.return_type, true)), ($(args)))\n")
                end
            end

            if f.return_type == "ErrorCode"
                write(out, """
function $(f.name)($argnames)
    err = @ccall lib.$(f.name)($rhs_args)::$(translate_type(f.return_type, true))
    if err != 0
        s = unsafe_string(error_string(err))
        error(s)
    end
    nothing
end
""")
            else
                write(out, """
function $(f.name)($argnames)
    @ccall lib.$(f.name)($rhs_args)::$(translate_type(f.return_type, true))
end
""")        
            end
        end
    end

    write(out, "\n\nend")

end







function main()
    cd(@__DIR__)
    in = open("src/exports.zig", "r")
    sin = read(in, String)
    close(in)

    functions = get_functions(sin)

    in = open("src/events.zig", "r")
    sin = read(in, String)
    close(in)
    
    constants = get_constants(sin)
    
    c_header = open("zig-out/include/picturalib.h", "w")
    write_c_header(c_header, constants, functions)
    close(c_header)

    jl_module = open("../src/PicturaLib.jl", "w")
    write_jl_module(jl_module, constants, functions)
    close(jl_module)
    
end

main()